### ISSUE TITLE
retain flag

### ISSUE THREAD

**Issue by seriousme** [sandro-k/mqtt-lens#1]
Hi,

thanks for creating MQTT-lens.
Would it be possible to add the "retain" option on messages to be published, e.g.:

```
var message = {
  topic: '/hello/world',
  payload: 'abcde', // or a Buffer
  qos: 0, // 0, 1, or 2
  retain: false // or true
};
```

(source: https://github.com/mcollina/mosca/wiki/Mosca-basic-usage#sending-data-from-mosca-to-clients)
Having this flag would enable me to publish a message and then have another client  pick it up as the first message after connect.

Cheers,
Hans

**Comment by sandro-k** [comment]
It is already in the source I just need to make a release to the Chrome-Store

**Comment by seriousme** [comment]
Great, I'll wait for the release then.

Thx
